import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../../components/Layout';
import ShoeGrid from '../../components/ShoeGrid';
import SHOES from '../../utils/SHOES';

const Home: NextPage = () => {
  return (
    <div data-testid='home'>
      <Head>
        <title>Sole & Ankle</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Layout>
        <ShoeGrid shoes={SHOES} />
      </Layout>
    </div>
  );
};

export default Home;
